### GET all movies
GET http://localhost:1234/movies

### GET one movie
GET http://localhost:1234/movies/c5daaba8-bdac-11f0-9ac3-324c9028faa7

### GET movie by genre
GET http://localhost:1234/movies?genre=DRAma

### POST create movie
POST http://localhost:1234/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM movies",
    "title": "The Shawshank Redemption",
    "year": 1995,
    "director": "Frank Darabont",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": ["Drama"],
    "rate": 9.3
}

### PATCH update movie
PATCH http://localhost:1234/movies/23e0b890-bdb5-11f0-9ac3-324c9028faa7
Content-Type: application/json

{
    "year": 1955
}

### DELETE delete movie
DELETE http://localhost:1234/movies/23e0b890-bdb5-11f0-9ac3-324c9028faa7